# Application & Automation Configuration
app.url=http://localhost:8088
browser=chrome
headless=false
timeout.implicit=5
timeout.explicit=10

# Database Configuration (In-Memory H2 Engine for SQL Verification)
db.driver=org.h2.Driver
db.url=jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1;MODE=MySQL
db.user=sa
db.password=

# Reporting Configuration
report.path=test-output/ExtentReport.html
report.title=DataShield E-Commerce & DB Validation Automation Report
report.name=E2E Selenium & SQL Database Automation Suite
